# Site settings
title: Percy - Latter equals never # replace by your title
email: xhc_1007@163.com # your email address
name: Percy .
# twitter: # your twitter id
url:  # site url
description: "Null."

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty

# This is my plugins section
plugins:
  - jekyll-mermaid

mermaid:
  src: '/assets/mermaid-9.1.1/mermaid.core.js'